services:
    spark:
        hostname: spark
        container_name: spark
#        image: "spark"
        build:
            context: ./spark
        ports:
            - "8050:8050"  # Spark master
            - "8051:8051"  # Spark worker
            - "7078:7078"
            - "10000:10000"  # ThriftServer JDBC endpoint
        healthcheck:
            test: [ "CMD", "curl", "--http0.9", "-f", "http://localhost:10000" ]
            interval: 20s
            retries: 5

    ontop:
        hostname: ontop
        container_name: ontop
        image: chimerasuite/ontop:fd38fec7a0
        environment:
            - "ONTOP_ONTOLOGY_FILE=/opt/ontop/input/datatypes.owl"
            - "ONTOP_MAPPING_FILE=/opt/ontop/input/datatypes.obda"
            - "ONTOP_PROPERTIES_FILE=/opt/ontop/input/datatypes.properties"
        #            - "ONTOP_VIEWS_FILE=/opt/ontop/input/datatypes_views.json"
        ports:
            - "8080:8080"
        volumes:
            - "./ontop-endpoint/input:/opt/ontop/input"
            - "./ontop-endpoint/jdbc:/opt/ontop/jdbc"
        restart: unless-stopped
        depends_on:
            spark:
                condition: service_healthy

networks:
    default:
        name: test-datatypes